export const STRING_COMMA: ",";
export const STRING_EMPTY: "";
export const STRING_PIPE: "|";
export const STRING_DOUBLE_PIPE: "||";
export const STRING_A: "a";
export const STRING_B: "b";
export const STRING_DEL: "del";
export const STRING_FUNCTION: "function";
export const STRING_INDEXES: "indexes";
export const STRING_INVALID_FIELD: "Invalid field";
export const STRING_INVALID_FUNCTION: "Invalid function";
export const STRING_INVALID_TYPE: "Invalid type";
export const STRING_OBJECT: "object";
export const STRING_RECORD_NOT_FOUND: "Record not found";
export const STRING_RECORDS: "records";
export const STRING_REGISTRY: "registry";
export const STRING_SET: "set";
export const STRING_SIZE: "size";
export const INT_0: 0;
export const INT_1: 1;
export const INT_3: 3;
export const INT_4: 4;
export const INT_8: 8;
export const INT_9: 9;
export const INT_16: 16;
